In [2]:
#importing the libraries
import numpy as py
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)          #if male is '0' -then female is '1'
dataset                                                  #if smoker is '0'- then smoker is'1'  so use(drop_first=True)

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['mse','mae','friedman_mse'],
           'max_features':['auto','sqrt','log2'],
           'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(indep,dep)

C:\Users\ELCOT\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:  1.4min finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [10]:
re=grid.cv_results_
print("The r_score value for best parameter {}:".format(grid.best_params_))

The r_score value for best parameter {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'best'}:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.013439,0.003420,0.004037,0.004349,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.702371,0.653946,0.711686,0.689334,0.025311,8
1,0.007405,0.003792,0.010755,0.000957,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.695116,0.651586,0.658005,0.668236,0.019187,10
2,0.010769,0.000933,0.003356,0.003414,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.729900,0.711053,0.688222,0.709725,0.017041,1
3,0.007398,0.003791,0.004713,0.003788,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.606642,0.560476,0.678782,0.615300,0.048684,15
4,0.010092,0.000025,0.002029,0.000006,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.682612,0.481916,0.718493,0.627674,0.104102,12
5,0.007403,0.003794,0.003372,0.004769,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.594787,0.666039,0.613322,0.624716,0.030184,14
6,0.171029,0.021808,0.041052,0.056630,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.675736,0.715354,0.677890,0.689660,0.018189,7
7,0.171922,0.013675,0.010081,0.000018,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.656466,0.729287,0.695300,0.693684,0.029751,5
8,0.168291,0.003383,0.007408,0.005306,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.605607,0.607483,0.693484,0.635525,0.040991,11
9,0.117642,0.061696,0.041095,0.056689,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.614011,0.549692,0.529148,0.564284,0.036149,18
10,0.077794,0.058833,0.073997,0.046882,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.703612,0.675018,0.680063,0.686231,0.012461,9
11,0.031570,0.000953,0.107492,0.009342,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.576475,0.640222,0.657727,0.624808,0.034916,13
12,0.011447,0.000963,0.006047,0.004357,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.709051,0.663055,0.707918,0.693341,0.021421,6
13,0.012104,0.000015,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.678015,0.721600,0.689906,0.696507,0.018396,4
14,0.013455,0.003395,0.004705,0.003793,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.683692,0.702227,0.710647,0.698855,0.011260,3
15,0.009407,0.000972,0.003356,0.003411,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.581334,0.657512,0.571007,0.603284,0.038576,17
16,0.013438,0.003411,0.003364,0.004757,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.700914,0.757449,0.657717,0.705360,0.040837,2
17,0.009416,0.000962,0.004033,0.002838,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.632515,0.596539,0.608924,0.612660,0.014923,16

In [13]:
age_input=int(input("Enter age:"))
BMI_input=(input("Enter BMI:"))
children_input=int(input("Enter Children:"))
sex_male_input=int(input("Enter Sex_Male 0 or 1:"))
Smoker_input=int(input("Enter Smoker_yes 0 or 1:"))

Enter age:44
Enter BMI:200
Enter Children:5
Enter Sex_Male 0 or 1:1
Enter Smoker_yes 0 or 1:0

In [15]:
Future_prediction=grid.predict([[age_input,BMI_input,children_input,sex_male_input,Smoker_input]])

In [18]:
Future_prediction

array([11033.6617])